title:             Allan Chang
email:             bohanzhang@my.unt.edu
description:       Made By Christ For Christ
author:            allan chang
baseurl:           ""
url:               "http://allan-chang.com"

# Social Profiles
twitter_username:  allan950404
github_username:   allan9595
facebook_username: 100007749556813
instagram_username: allan_chang95
# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

